all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    docker:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
  vars:
    project_root: "{{ playbook_dir }}/.."
    docker_compose_file: "{{ project_root }}/docker-compose.yml"
    environment_file: "{{ project_root }}/.env" 